## Finding rmp of a particular profile (generated by R) in a population of size N
## rmp match needs: N = population size, r = number of loci <= 15, s = number of alleles for each loci (equal probs)
## Used for validation

rmp <- function(N, r, s){
  
  # naming r loci: loci1, loci2, loci3, .... , locir  
  rloci <- vector(length = r)
  
  for(i in 1:r)    {
    
    rloci[i] <- paste("locus", i, sep="", collapse="")
    
  } 
  
  
  
  #creating pop
  population <- data.frame(matrix(nrow=N, ncol= r+1))
  colnames(population) <- c("ID", rloci)
  population[, 1] <- 1:N
  
  ## generating N profiles and filling in population database. each loci has 10 alleles
  for(j in 1:r) {
    allele <- sample(1:s, N, replace = TRUE)
    tmp_df <- data.frame(A1 = as.integer(sample(allele, N, 
                                                replace = TRUE)),
                         A2 = as.integer(sample(allele, N, 
                                                replace = TRUE))
    )
    population[, j+1] <- data.frame(as.integer(sample(allele, N, 
                                                      replace = TRUE)))
  }
  
  
  # Creating a random profile to find the rmp of
  allelesamples <- sample(1:s, N , replace = TRUE)
  alleles <- vector(length = r)
  
  
  prof <- data.frame(matrix(nrow=1, ncol= r+1))
  colnames(prof) <- c("NAME", rloci)
  
  prof[, 1] <- "SUSPECT"
  
  for(k in 1:r){
    alleles[k] <- sample(allelesamples, 1)
  }
  
  prof[,1:r+1] <- alleles
  
  match <- inner_join(prof, population)
  
  return(as.numeric(nrow(match)/N))
  
}