---
title: "new.sims"
author: "Steph"
date: "1/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(parallel)
library(profvis)
library(data.table)
library(prodlim)
library(dplyr)
library(sqldf)
library(DBI)
library(RSQLite)
library(readxl)
library(pbmcapply)
```


```{r}
  # naming r loci: loci1, loci2, loci3, .... , locir  
  rloci <- vector(length = r)
  
  for(i in 1:r)    {
    
    rloci[i] <- paste("loci", i, sep="", collapse="")
    
  } 
  
  #creating pop
  population <- data.frame(matrix(nrow=N, ncol= r+1))
  colnames(population) <- c("ID", rloci)
  population[, 1] <- 1:N
  
  ## generating N profiles and filling in population database. each loci has 10 alleles
  for(j in 1:r) {
    allele <- sample(1:s, N, replace = TRUE)
    tmp_df <- data.frame(A1 = as.integer(sample(allele, N, 
                                                replace = TRUE)),
                         A2 = as.integer(sample(allele, N, 
                                                replace = TRUE))
    )
    population[, j+1] <- data.frame(as.integer(sample(allele, N, 
                                                      replace = TRUE)))
  }
  
  
  
  offenders <- sample_n(population, N*p, replace = FALSE)  ## offenders is randomly chosen from the population, not just the first p percent. 
  colnames(offenders) <- c("off ID", rloci)
  nonoffenders <- population[!(apply(population, 1, toString) %in% apply(offenders, 1, toString)), ] # populuation - offenders
  colnames(nonoffenders) <- c("non-off ID", rloci)
  
  # checking for duplicates between offenders and non-offenders
  false.matches <- inner_join(offenders, nonoffenders)
  
  ## probability = # of false detects / N
  return(nrow(false.matches)/N)

```


```{r}
nsims <- 10^4
N <- 10000
p <- 0.1
r <- 6
s <- 10

n.core <- 10
tmp <- vector("list", nsims)

time <- system.time({
  results <- unlist(pbmclapply (tmp, FUN = function(y) {
                  collisions(N,p,r,s) },
                  mc.cores = n.core))
})


sum(results)/length(results)
closeAllConnections()

N*p*(1-p)*(1/s^r)
```












