---
title: "partjoin2"
author: "Steph"
date: "6/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(parallel)
library(profvis)
library(data.table)
library(prodlim)
library(dplyr)
library(sqldf)
library(DBI)
library(RSQLite)
library(readxl)
library(pbmcapply)
```


```{r}
source("Functions/partjoin.R")
source("Functions/popconfigure.R")
source("Functions/popdt.R")
```

```{r}
#Read in excel file dataframe 
PopSource <- read.csv("Pop_Source.csv", header=FALSE, stringsAsFactors=FALSE)

PopSource <- popconfigure(PopSource)
population <- popdt(N, PopSource)
```

```{r}
advcollision <- function(population,p,nmatch){
  stopifnot(N > 1000, is.numeric(N), is.data.frame(PopSource),
            dim(PopSource)[2] == 26, !is.null(PopSource))

  N <- nrow(population)
  
  offenders <- sample_n(population, N*p, replace = FALSE)

  
  ## finding the non-offenders -- population-offenders
  dB_1 <- dbConnect(RSQLite::SQLite(), ":memory:") ## "" 
  dbWriteTable(dB_1, "population", population, overwrite = TRUE)
  dbWriteTable(dB_1,"offenders", offenders, overwrite=TRUE)
  nonoffenders <- dbGetQuery(dB_1, "SELECT *
                    FROM population 
                    WHERE ID NOT IN
                              (SELECT ID
                              FROM offenders)")
  

  
  # checking for duplicates between offenders and non-offenders, this only works for 13 loci
  #false.matches <- inner_join(offenders, nonoffenders)
  
  ## probability = # of false detects . partjoin() returns the # of matches found. 
  false.matches <- partjoin(DB1 = offenders, DB2 = nonoffenders, nmatch)
  return(false.matches/(p*(1-p)*N*N))

}

```



```{r}
nsims <- 1
N <- 1000000
p <- 0.01
nmatch <- 9

n.core <- 28
tmp <- vector("list", nsims)

time <- system.time({
  results <- unlist(pbmclapply(tmp, FUN = function(y){
                  advcollision(population,p,nmatch)},
                  mc.cores = n.core))
})

results
sum(results)/length(results)
closeAllConnections()

```

```